# Generated by Django 4.2 on 2023-05-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemaroom',
            name='room_name',
            field=models.CharField(default='Room 1', max_length=20),
        ),
        migrations.AddField(
            model_name='cinemaroom',
            name='total_seat',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='cinemaroom',
            name='room_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='moviesession',
            name='session_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
