# Generated by Django 4.2.1 on 2023-05-15 08:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('avatar', models.ImageField(default='avatar.jpg', upload_to='profile_avatars')),
                ('seat_preference', models.CharField(default='Front', max_length=50)),
                ('loyalty_points', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='moviesession',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 15, 16, 7, 3, 675353)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='purchased_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 15, 16, 7, 3, 676346)),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
