# Generated by Django 4.2 on 2023-05-01 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cinemaroom_room_name_cinemaroom_total_seat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesession',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 1, 16, 37, 22, 436558)),
        ),
    ]
