# Generated by Django 4.2 on 2023-05-02 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
        ('main', '0003_moviesession_start_time'),
    ]

    operations = [
    ]
