# Generated by Django 4.2 on 2023-05-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_seat_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_duration',
            field=models.CharField(default='2:00', max_length=20),
        ),
    ]
