# Generated by Django 4.2 on 2023-05-02 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_ticket_cost_ticket_ticket_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesession',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 2, 23, 6, 28, 787796)),
        ),
    ]
