# Generated by Django 4.2 on 2023-05-03 04:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_moviesession_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_duration',
            field=models.FloatField(default=2, max_length=20),
        ),
        migrations.AlterField(
            model_name='moviesession',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 3, 12, 17, 6, 91067)),
        ),
    ]
