# Generated by Django 4.2 on 2023-05-14 09:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0015_alter_moviesession_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodAndDrinks',
            fields=[
                ('combo_id', models.AutoField(primary_key=True, serialize=False)),
                ('combo_name', models.CharField(default='Popcorn and Coke', max_length=50)),
                ('combo_price', models.FloatField(default=10, max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='purchased_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 14, 17, 0, 26, 468179)),
        ),
        migrations.AlterField(
            model_name='moviesession',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 14, 17, 0, 26, 466180)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='cost',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('avatar', models.ImageField(default='avatar.jpg', upload_to='profile_avatars')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='ticket',
            name='combo_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.foodanddrinks'),
        ),
        migrations.DeleteModel(
            name='FoodAndBeverage',
        ),
    ]
