# Generated by Django 4.2.1 on 2023-05-14 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_userprofile_alter_user_user_type_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_type_id',
            new_name='user_type',
        ),
    ]
