# Generated by Django 4.2.1 on 2023-05-18 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_suspensionstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='suspension_status',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='register.suspensionstatus'),
        ),
    ]
