# Generated by Django 4.2.1 on 2023-05-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_userprofile_suspension_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='suspension_status',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='SuspensionStatus',
        ),
    ]
