# Generated by Django 4.2.1 on 2023-05-18 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_alter_userprofile_suspension_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='suspension_status',
            new_name='suspend',
        ),
    ]
